-- Tabela de Equipamentos
CREATE TABLE equipamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(40) NOT NULL,
    descricao VARCHAR(120) NOT NULL
);

-- Tabela de Professores
CREATE TABLE professor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email_institucional VARCHAR(160) UNIQUE
);

-- Tabela de Reservas com chaves estrangeiras
CREATE TABLE reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamento_id BIGINT NOT NULL,
    professor_id BIGINT NOT NULL,
    sala VARCHAR(20) NOT NULL,
    retirada TIMESTAMP NOT NULL,
    entrega TIMESTAMP NOT NULL,

    CONSTRAINT fk_reserva_equipamento FOREIGN KEY (equipamento_id) REFERENCES equipamento(id),
    CONSTRAINT fk_reserva_professor FOREIGN KEY (professor_id) REFERENCES professor(id)
);