-- Migration: V1__criar_tabelas.sql
-- Responsável por criar as tabelas iniciais do projeto HealthBet
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(120) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    phone VARCHAR2(30),
    birthdate DATE
);


-- Migration: V2__carga_inicial.sql
-- Inserção de usuários iniciais para teste

INSERT INTO users (name, email, phone, birthdate)
VALUES
('Pedro Almeida', 'pedro@email.com', '11999999999', '20-05-2021'),

